# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metab', '0002_CUSTOM_IMPORT_DATA'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannotation',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
