# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mbrowse', '0002_CUSTOM_IMPORT_DATA'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannotationdownload',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user requesting download', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cannotationdownloadresult',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user requesting download', null=True, on_delete=django.db.models.deletion.CASCADE, to='mbrowse.CAnnotationDownload'),
        ),
    ]
