# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbrowse', '0003_auto_20180820_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannotationdownloadresult',
            name='user',
        ),
    ]
