# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbrowse', '0005_cannotationdownloadresult_cannotationdownload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cannotationdownloadresult',
            old_name='canns_file',
            new_name='annotation_file',
        ),
    ]
